#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Executando validações antes do push..."

# Executa ESLint
echo "🔍 Executando ESLint..."
npm run lint

# Verifica tipos TypeScript
echo "🔎 Verificando tipos TypeScript..."
npm run type-check

