export const signupComponents = {
    inpSignupGenderMr: ".login-form form label[for='id_gender1'] input",
    inpSignupGenderMrs: ".login-form form label[for='id_gender2'] input",
    inpPassword: '#password',
    ddlBirthDay: '#days',
    ddlBirthMonth: '#months',
    ddlBirthYear: '#years',
    chkNewsletter: "#uniform-newsletter input",
    chkOffers: "#uniform-optin input",
    inpFirstName: "#first_name",
    inpLastName: "input[data-qa='last_name']",
    inpCompany: "#company",
    inpAddress1: "#address1",
    inpAddress2: "#address2",
    inpCountry: '#country',
    inpState: "#state",
    inpCity: "#city",
    inpZipcode: "#zipcode",
    inpMobileNumber: "#mobile_number",
    btnCreateAccount: "button[data-qa='create-account']",
}